version: '3'
services:
  web:
    build:
      context: .
      target: ${TARGET:-development}
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
